#!/usr/bin/env node
/**
 * Bundles @novnc/novnc + connection logic into a self-contained HTML string
 * and generates src/assets/novncHtml.ts for use in VncConsoleScreen WebView.
 *
 * Run: node scripts/build-novnc.js
 */

const esbuild = require('esbuild');
const fs = require('fs');
const path = require('path');

const ENTRY = path.join(__dirname, 'novnc-entry.js');
const OUT_TS = path.join(__dirname, '../src/assets/novncHtml.ts');

async function main() {
  const result = await esbuild.build({
    entryPoints: [ENTRY],
    bundle: true,
    format: 'esm',
    minify: true,
    write: false,
    platform: 'browser',
    target: ['es2022'],
  });

  const bundleJs = result.outputFiles[0].text;

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
  <title>VNC Console</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    html, body { width: 100%; height: 100%; background: #000; overflow: hidden; }
    #screen { width: 100%; height: 100%; }
    #status {
      position: fixed; bottom: 0; left: 0; right: 0;
      background: rgba(0,0,0,0.7); color: #aaa;
      font: 12px/24px monospace; text-align: center; padding: 0 8px;
      pointer-events: none;
    }
  </style>
</head>
<body>
  <div id="screen"></div>
  <div id="status">Connecting...</div>
  <script type="module">${bundleJs}</script>
</body>
</html>`;

  const tsContent = `// AUTO-GENERATED by scripts/build-novnc.js - do not edit manually
// Regenerate with: node scripts/build-novnc.js

export const novncHtml = ${JSON.stringify(html)};

/**
 * Builds URL hash params to be appended to the HTML base URL.
 * Used by VncConsoleScreen to pass WSS URL and password to the inline page.
 */
export function buildNovncHash(wssUrl: string, password: string): string {
  return \`#wss=\${encodeURIComponent(wssUrl)}&pass=\${encodeURIComponent(password)}\`;
}
`;

  fs.writeFileSync(OUT_TS, tsContent, 'utf8');
  console.log(`✓ noVNC bundle written to src/assets/novncHtml.ts (${(bundleJs.length / 1024).toFixed(0)} KB JS)`);
}

main().catch(e => { console.error(e); process.exit(1); });
